trash: ''
width: 30
height: 30
cell_size: 20
tail_length: 15
reward_for_step: -0.01
penalty_for_death: 4
lose_by_enemy: 2.5
enemy_kill_reward: 5
enemy_count: 1
enemy_behavior: random
step_closer_to_enemy_reward: 0.3
step_further_from_enemy_penalty: 0.1